[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Trvos/link.ld",
]

[profile.release]
panic = "abort"
lto = true
strip = true
opt-level = "z"  # Optimize for size.