[package]
name = "rvos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = { version = "0.11" }
talc = { version = "4" }
spin = "0"
log = "0"
